id: P08F8C344
initial_creation_type: input
source_metadata:
  title: Jigme Lingpa Series
  language: es
  description: A series of texts by and about the great Dzogchen master Rigdzin Jigme
    Lingpa (rig 'dzin 'jigs med gling pa, 1730–1798), who revealed the Longchen Nyingtik
    (klong chen snying thig) collection.
  volume:
    05ec5e103b204538924c8507adf0e854:
      title: An Aspiration for the Final Age
      parent: Aspiration Prayers
    a599f70cdf9f41cea75894607f8f96ab:
      title: Aspiration to Be Reborn in the Realm of Sukhāvatī
      parent: Aspiration Prayers
    a555db4b39aa43fdbda7343b7ed7cd27:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: Aspiration Prayers
    b56773d456654317ac40e97985e169a9:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Aspiration Prayers
    75da8751d09c4e9d99c2e71e7de7c90d:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Aspiration Prayers
    f9f87aefda894c5e8bb8d56a3f9ec998:
      title: 'Precise Discernment of Dharmas: A Catalogue of the Complete Collected
        Works of the Omniscient King of Dharma, Rigdzin Jigme Lingpa'
      parent: Catalogues
    9c9e60281dda4597a2fdcb7621e6dbf4:
      title: 'Elucidating the Body Maṇḍala: Clarifications on the Recitation Manual
        of the Female Practice of the Queen of Great Bliss'
      parent: Commentaries
    f2a1bc4fcf844d7c8841f97288d04921:
      title: Main Recitation Manual for the Female Practice of the Queen of Great
        Bliss
      parent: Commentaries
    712e070c71534005ae2302499350881c:
      title: 'The Casket of Siddhis: A Recitation Manual for “Vidyādhara Assembly”
        (Rigdzin Düpa)'
      parent: Commentaries
    6de97ae730f94108ada4d59787583a10:
      title: 'The Loud Drum of Spring: A Commentary on the Difficult Points of the
        Ritual of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Commentaries
    4d66c02ad2244a87afbed1d700b0ca38:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Commentaries
    285bf94632fb404383df9257fa33d018:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Confession
    220a9600bb034fa092e14fec5d1d0128:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Dharma Protectors
    272baf06498345a7b4fa9d3a97b8b611:
      title: Vajra Verses on the Natural State
      parent: Dzogchen
    e5e016762ea8443482c9ac214ff699ce:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Empowerment Rites
    cd507302755d43f2889e888d8492cbd8:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Empowerment Rites
    c45ba4757f6843cc8c78c5fac9da0ad4:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Empowerment Rites
    485a45b91d5d4f828c963655c806a69b:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Guru Rinpoche Prayers
    38db2518a930475694dd8e7c827b85ac:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Guru Rinpoche Prayers
    f1c67b08649a47f3bb1ab0d247a74afe:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Guru Rinpoche Prayers
    41d74df050bf40d29ca4916db9b31016:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    d87ff271d44a40d7bc94fdf3e48e03ce:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Guru Rinpoche Prayers
    ca64c7847efc4227a4d2f31d24a35e9d:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Guru Yoga
    1fb15f8734664b94a262276b7894e6ff:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Guru Yoga
    7745407eebbc4164a0fcdd7875a0f329:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: History
    44d51cd38b234ee9a400fd052ee9c706:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    4760a75478484dfb861769ce5a59ad4d:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Lineage Prayers
    e534bca6bf914b95accb5d30b844bd8d:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Longchen Nyingtik
    4bf42c6b356a4835901bd35182fa5c27:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    2e9038655375428f98934d07a9166e76:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Pilgrimage
    ed94392e15624210bf721284e3174f42:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Practices
    7a1c0954db244a388d603e0aec5eb5ea:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Practices
    f2ba583bb77949c0bb9fbd80a78e16c8:
      title: Descent of Blessings of the Eight Vidyādharas
      parent: Practices
    48994f4aee7141018bd4cafef20bb6e6:
      title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
      parent: Practices
    2eefca3abc084092b70a16a7b6e715e3:
      title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female
        Awareness-Holder (Yumka)'
      parent: Practices
    8570f0fac7884e85968a161f9a240703:
      title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day
        Vows of a Lay Practitioner'
      parent: Practices
    7403ef1c332141078561bfb8c7d7c270:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      parent: Practices
    69e2d8044ffd4f42b8de9f83cd5744c3:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Practices
    1a70a9683abf4b6482225f03f2c43c4c:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Practices
    6caa16592e274a5a8072cd2ded376db2:
      title: In Praise of Jigme Lingpa’s Pre-Eminence
      parent: Praise
    181a888acbee415da4e53733aeae06a9:
      title: In Praise of the Goddess Mārīcī (Özerchenma)
      parent: Praise
    91f456c3989148bd8e8204dd912a55cf:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    d9af2eb9cb8b47e982f1e048916b8e45:
      title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept
        Rangjung Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
      parent: Prayers
    6059cf54bc7d412daf6d3aeedeec23ba:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Prayers
    7c56557ebc0e4d5e86b8c7a7c593638c:
      title: 'Devotion that Pierces the Heart: A Prayer to the Omniscient Jigme Lingpa'
      parent: Prayers
    c5b90734e66f483888ac9a097be47ceb:
      title: Prayer to Rigdzin Jigme Lingpa Invoking His Previous Incarnations
      parent: Prayers
    0f60d9842e424756891bd0ca8d9033f0:
      title: Prayer to the Garland of Rebirths of the Dzogchenpas of Eastern Tibet
      parent: Prayers
    f66cf8d7dd754c579caf0576ac42b7a8:
      title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
      parent: Prayers
    4087a6441e304e3ea27bd4bcbf94bdb3:
      title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
      parent: Prayers
    7b9f16b539fd4f1d91b71dc38940435d:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Sādhanas
    21a82503544945a9ba7883c08015848d:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    ee37835f96fd44f29b7662194cf8bc68:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Sādhanas
    294d5fcc9aa04d8a9d49dc996ec73717:
      title: 'Adornment of Lord Nāgārjuna’s Wisdom Mind: The Fourfold Maṇḍala Offering
        to Tārā'
      parent: Sādhanas
    961a9dc89b5d430c84a5ab6a35e20559:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Sādhanas
    04a44fbb859b4d799a0d0baf8d75ddb5:
      title: Sādhana of the Great Master Vairotsana
      parent: Sādhanas
    13487787a9d34d4eaf117630e039cd02:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Sādhanas
    d80fec642039441897907904f8dce9b1:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Sādhanas
    5d29809faf024b3891cf9aef6a3eed16:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Transference (Phowa)
    fcbc1d26561640cda08b6ef3f8fd0f73:
      title: Brief Prayer of the Feast Gathering
      parent: Tsok
    053f90f05a5b4ae3b658b43622974786:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Tsok
    10dd637f390048aa909f65e1044d5a55:
      title: Song of the Feast (Tsok Lu)
      parent: Tsok
    480a368cd07e4c40be1754b5242f6eee:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Calling the Guru from Afar
created_at: '2022-03-01T00:07:12.487781'
last_modified_at: '2022-03-01T00:07:12.487783'
